// automatically generated by the FlatBuffers compiler, do not modify

package fbtypes

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type VnodeIdBytesErrList struct {
	_tab flatbuffers.Table
}

func GetRootAsVnodeIdBytesErrList(buf []byte, offset flatbuffers.UOffsetT) *VnodeIdBytesErrList {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &VnodeIdBytesErrList{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *VnodeIdBytesErrList) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *VnodeIdBytesErrList) L(obj *VnodeIdBytesErr, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		if obj == nil {
			obj = new(VnodeIdBytesErr)
		}
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *VnodeIdBytesErrList) LLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func VnodeIdBytesErrListStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func VnodeIdBytesErrListAddL(builder *flatbuffers.Builder, L flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(L), 0)
}
func VnodeIdBytesErrListStartLVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func VnodeIdBytesErrListEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
