// automatically generated by the FlatBuffers compiler, do not modify

package gentypes

import (
	flatbuffers "github.com/google/flatbuffers/go"
	"github.com/ipkg/go-chord/fbtypes"
)

type TransferRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsTransferRequest(buf []byte, offset flatbuffers.UOffsetT) *TransferRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &TransferRequest{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *TransferRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *TransferRequest) Src(obj *fbtypes.Vnode) *fbtypes.Vnode {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(fbtypes.Vnode)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *TransferRequest) Dst(obj *fbtypes.Vnode) *fbtypes.Vnode {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(fbtypes.Vnode)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func TransferRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func TransferRequestAddSrc(builder *flatbuffers.Builder, Src flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(Src), 0)
}
func TransferRequestAddDst(builder *flatbuffers.Builder, Dst flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(Dst), 0)
}
func TransferRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
