// automatically generated by the FlatBuffers compiler, do not modify

package gentypes

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type VnodeIdTxErrList struct {
	_tab flatbuffers.Table
}

func GetRootAsVnodeIdTxErrList(buf []byte, offset flatbuffers.UOffsetT) *VnodeIdTxErrList {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &VnodeIdTxErrList{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *VnodeIdTxErrList) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *VnodeIdTxErrList) L(obj *VnodeIdTxErr, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		if obj == nil {
			obj = new(VnodeIdTxErr)
		}
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *VnodeIdTxErrList) LLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func VnodeIdTxErrListStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func VnodeIdTxErrListAddL(builder *flatbuffers.Builder, L flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(L), 0)
}
func VnodeIdTxErrListStartLVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func VnodeIdTxErrListEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
