// automatically generated by the FlatBuffers compiler, do not modify

package gentypes

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type VnodeIdsTx struct {
	_tab flatbuffers.Table
}

func GetRootAsVnodeIdsTx(buf []byte, offset flatbuffers.UOffsetT) *VnodeIdsTx {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &VnodeIdsTx{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *VnodeIdsTx) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *VnodeIdsTx) Ids(obj *ByteSlice, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		if obj == nil {
			obj = new(ByteSlice)
		}
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *VnodeIdsTx) IdsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *VnodeIdsTx) Tx(obj *Tx) *Tx {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(Tx)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func VnodeIdsTxStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func VnodeIdsTxAddIds(builder *flatbuffers.Builder, Ids flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(Ids), 0)
}
func VnodeIdsTxStartIdsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func VnodeIdsTxAddTx(builder *flatbuffers.Builder, Tx flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(Tx), 0)
}
func VnodeIdsTxEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
