// automatically generated by the FlatBuffers compiler, do not modify

package gentypes

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type VnodeIdInodeErrList struct {
	_tab flatbuffers.Table
}

func GetRootAsVnodeIdInodeErrList(buf []byte, offset flatbuffers.UOffsetT) *VnodeIdInodeErrList {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &VnodeIdInodeErrList{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *VnodeIdInodeErrList) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *VnodeIdInodeErrList) L(obj *VnodeIdInodeErr, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		if obj == nil {
			obj = new(VnodeIdInodeErr)
		}
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *VnodeIdInodeErrList) LLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func VnodeIdInodeErrListStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func VnodeIdInodeErrListAddL(builder *flatbuffers.Builder, L flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(L), 0)
}
func VnodeIdInodeErrListStartLVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func VnodeIdInodeErrListEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
